# https://rust-lang.github.io/rustup/concepts/components.html
[toolchain]
channel = "nightly-2023-03-05"
components = [ "rustc", "cargo", "rustfmt", "rust-std", "rust-docs", "rust-analyzer", "clippy", "miri", "rust-src", "llvm-tools-preview" ]
targets = [ "wasm32-unknown-unknown" ]
profile = "default"
